name: My first and very basic workflow

#on: push # this is called trigger 
on: 
 workflow_dispatch:
jobs: 
    first_job:
        runs-on: self-hosted
        steps:
        - name: testing chekout repo with checkout action
          uses: actions/checkout@v6
        - name: welcome to the github-actions
          run: echo "my first github actions job"

        - name: list files
          run: ls -la

        - name: Read files
          run: cat README.md

        - name: list the disk space
          run: df -h

