name: My first and very basic workflow

#on: push # this is called trigger 
on: [push]

jobs: 
    first_job:
        runs-on: self-hosted
        steps:
        - name: welcome to the github-actions
          run: echo "my first github actions job"

        - name: list files
          run: ls

            #        - name: Read files
            #          run: cat README.md

        - name: list the disk space
          run: df -h

