name: Test Kubernetes Access

on:
workflow_dispatch:

jobs:
test:
runs-on: self-hosted

steps:
  - name: Set KUBECONFIG
    run: |
      mkdir -p $HOME/.kube
      echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

  - name: Check cluster
    run: kubectl get nodes
