name: Test Self Hosted Runner

on:
  workflow_disatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Check runner
        run: |
          echo "Runner is working 🚀"
          hostname
          whoami
          uname -r
          df -h
